# Build settings
gems:
  - jemoji
  - jekyll-paginate

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Site settings
title: Guillermo Orellana
description: May contain traces of sarcasm and siesta
email: wiyarmir@gmail.com
#favicon
favicon: /favicon.png

email: guillermo.orellana.ruiz@gmail.com
#blog logo
logo: "/assets/images/df_logo.png"
# blog cover
cover: "/assets/images/oldstreet.jpg"

name: 'Guillermo Orellana'
author: 'Guillermo Orellana'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://guillermoorellana.es" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@wiyarmir'
ga_tracking_id: 'UA-58206969-1'

#fill in disqus shortname to use disqus
disqus: wiyarmir

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/wiyarmir
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/wiyarmir
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	https://uk.linkedin.com/in/guillermoorellana
    desc:	Find me on LinkedIn
    share_url:
    share_title:
    share_link:
