# Build settings
gems:
  - jemoji
  - jekyll-paginate

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Site settings
title: Guillermo Orellana
description: I promise this time I will update it regularly...
email: wiyarmir@gmail.com
#favicon
favicon: /favicon.png

email: guillermo.orellana.ruiz@gmail.com
#blog logo
logo: "/assets/images/df_logo.png"
# blog cover
cover: "/assets/images/oldstreet.jpg"

name: 'Guillermo Orellana'
author: 'Guillermo Orellana'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://guillermoorellana.es" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@wiyarmir'
ga_tracking_id: 'UA-58206969-1'

#fill in disqus shortname to use disqus
disqus: wiyarmir

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/wiyarmir
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/wiyarmir
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
